import JSZip from "jszip";
import { saveAs } from "file-saver";

interface ExportOptions {
  html: string;
  css: string;
  js: string;
  name?: string;
}

export async function exportWebsite({ html, css, js, name = "generated-website" }: ExportOptions) {
  const zip = new JSZip();

  // Create the full HTML file
  const fullHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="AI Generated Website">
  <title>Generated Website</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  ${html}
  <script src="script.js"></script>
</body>
</html>`;

  // Add files to zip
  zip.file("index.html", fullHtml);
  zip.file("styles.css", css);
  zip.file("script.js", js);

  // Add a README
  const readme = `# Generated Website

This website was generated by WebGen AI.

## Files
- \`index.html\` - Main HTML file
- \`styles.css\` - CSS styles
- \`script.js\` - JavaScript functionality

## Usage
Open \`index.html\` in your browser to view the website.

## Deployment
You can deploy this website to any static hosting service:
- Netlify
- Vercel
- GitHub Pages
- Any web server

Generated on: ${new Date().toISOString()}
`;

  zip.file("README.md", readme);

  // Generate and download
  const content = await zip.generateAsync({ type: "blob" });
  saveAs(content, `${name}.zip`);
}
